name: voxfable
description: "An AI-powered Story Buddy & Interactive Quiz mobile app for children, featuring ElevenLabs Text-to-Speech and dynamic gamified lessons."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  riverpod: ^3.3.2
  flutter_riverpod: ^3.3.2
  riverpod_annotation: ^4.0.3
  flutter_tts: ^4.2.5
  dio: ^5.7.0
  path_provider: ^2.1.3
  audioplayers: ^6.0.0
  rive: ^0.13.0
  confetti: ^0.7.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  crypto: ^3.0.7
  flutter_dotenv: ^6.0.1
  flutter_card_swiper: ^7.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^4.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/data/
    - assets/fonts/
    - assets/images/
    - assets/logo/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/poppins/Poppins-Black.ttf
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic